/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-09-28 06:02:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.authen;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Mirrored from html.themegenix.com/skillgro/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 16 Sep 2024 01:45:08 GMT -->\r\n");
      out.write("    <head>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/css-home.jsp", out, false);
      out.write("\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Scroll-top -->\r\n");
      out.write("            <button class=\"scroll__top scroll-to-target\" data-target=\"html\">\r\n");
      out.write("                <i class=\"tg-flaticon-arrowhead-up\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <!-- Scroll-top-end-->\r\n");
      out.write("\r\n");
      out.write("            <!-- header-area -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/header-home.jsp", out, false);
      out.write("\r\n");
      out.write("            <!-- header-area-end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- main-area -->\r\n");
      out.write("            <main class=\"main-area fix\">\r\n");
      out.write("\r\n");
      out.write("                <!-- breadcrumb-area -->\r\n");
      out.write("                <section class=\"breadcrumb__area breadcrumb__bg\" data-background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/bg/breadcrumb_bg.jpg\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"breadcrumb__content\">\r\n");
      out.write("                                <h3 class=\"title\">Student Login</h3>\r\n");
      out.write("                                <nav class=\"breadcrumb\">\r\n");
      out.write("                                    <span property=\"itemListElement\" typeof=\"ListItem\">\r\n");
      out.write("                                        <a href=\"index.html\">Home</a>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span class=\"breadcrumb-separator\"><i class=\"fas fa-angle-right\"></i></span>\r\n");
      out.write("                                    <span property=\"itemListElement\" typeof=\"ListItem\">Login</span>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"breadcrumb__shape-wrap\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/others/breadcrumb_shape01.svg\" alt=\"img\" class=\"alltuchtopdown\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/others/breadcrumb_shape02.svg\" alt=\"img\" data-aos=\"fade-right\" data-aos-delay=\"300\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/others/breadcrumb_shape03.svg\" alt=\"img\" data-aos=\"fade-up\" data-aos-delay=\"400\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/others/breadcrumb_shape04.svg\" alt=\"img\" data-aos=\"fade-down-left\" data-aos-delay=\"400\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/others/breadcrumb_shape05.svg\" alt=\"img\" data-aos=\"fade-left\" data-aos-delay=\"400\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- breadcrumb-area-end -->\r\n");
      out.write("\r\n");
      out.write("            <!-- singUp-area -->\r\n");
      out.write("            <section class=\"singUp-area section-py-120\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row justify-content-center\">\r\n");
      out.write("                        <div class=\"col-xl-6 col-lg-8\">\r\n");
      out.write("                            <div class=\"singUp-wrap\">\r\n");
      out.write("                                <h2 class=\"title\">Welcome back!</h2>\r\n");
      out.write("                                <p>Hey there! Ready to log in? Just enter your username and password below and you'll be back in action in no time. Let's go!</p>\r\n");
      out.write("                                <div class=\"account__social\">\r\n");
      out.write("                                    <a href=\"https://accounts.google.com/o/oauth2/auth?scope=email profile openid&redirect_uri=http://localhost:9998/SWP_OCMS/LoginGoogleHandler&response_type=code&client_id=257748132214-9811944a5anccchj9egqhg9qci33l5ij.apps.googleusercontent.com&approval_prompt=force\" class=\"account__social-btn\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/icons/google.svg\" alt=\"img\">\r\n");
      out.write("                                        Continue with google\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"account__divider\">\r\n");
      out.write("                                    <span>or</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <form action=\"authen?action=login\" class=\"account__form\" method=\"POST\" id=\"loginForm\">\r\n");
      out.write("                                    <div class=\"form-grp\">\r\n");
      out.write("                                        <label for=\"email\">Email</label>\r\n");
      out.write("                                        <input id=\"email\" name=\"email\" type=\"text\" placeholder=\"email\">\r\n");
      out.write("                                        <span class=\"error\" id=\"emailError\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-grp\">\r\n");
      out.write("                                        <label for=\"password\">Password</label>\r\n");
      out.write("                                        <input id=\"password\" name=\"password\" type=\"password\" placeholder=\"password\">\r\n");
      out.write("                                        <span class=\"error\" id=\"passwordError\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-two arrow-btn\">Sign In<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/icons/right_arrow.svg\" alt=\"img\" class=\"injectable\"></button>\r\n");
      out.write("                                    <div class=\"account__check\">\r\n");
      out.write("                                        <div class=\"account__check-remember\">\r\n");
      out.write("                                            <input type=\"checkbox\" class=\"form-check-input\" value=\"\" id=\"terms-check\">\r\n");
      out.write("                                            <label for=\"terms-check\" class=\"form-check-label\">Remember me</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"account__check-forgot\">\r\n");
      out.write("                                            <a href=\"authen?action=enter-email\">Forgot Password?</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <div class=\"account__switch\">\r\n");
      out.write("                                    <p>Don't have an account?<a href=\"authen?action=sign-up\">Sign Up</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- singUp-area-end -->\r\n");
      out.write("\r\n");
      out.write("        </main>\r\n");
      out.write("        <!-- main-area-end -->\r\n");
      out.write("\r\n");
      out.write("        <!-- footer-area -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/footer-home.jsp", out, false);
      out.write("\r\n");
      out.write("            <!-- footer-area-end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- JS here -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/js-home.jsp", out, false);
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            SVGInject(document.querySelectorAll(\"img.injectable\"));\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("                const form = document.getElementById('loginForm');\r\n");
      out.write("                const email = document.getElementById('email');\r\n");
      out.write("                const password = document.getElementById('password');\r\n");
      out.write("                const emailError = document.getElementById('emailError');\r\n");
      out.write("                const passwordError = document.getElementById('passwordError');\r\n");
      out.write("\r\n");
      out.write("                form.addEventListener('submit', function (event) {\r\n");
      out.write("                    let isValid = true;\r\n");
      out.write("\r\n");
      out.write("                    // Reset error messages\r\n");
      out.write("                    emailError.textContent = '';\r\n");
      out.write("                    passwordError.textContent = '';\r\n");
      out.write("\r\n");
      out.write("                    // Email validation\r\n");
      out.write("                    if (email.value.trim() === '') {\r\n");
      out.write("                        emailError.textContent = 'Email is required';\r\n");
      out.write("                        isValid = false;\r\n");
      out.write("                    } else if (!isValidEmail(email.value)) {\r\n");
      out.write("                        emailError.textContent = 'Please enter a valid email address';\r\n");
      out.write("                        isValid = false;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // Password validation\r\n");
      out.write("                    if (password.value.trim() === '') {\r\n");
      out.write("                        passwordError.textContent = 'Password is required';\r\n");
      out.write("                        isValid = false;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    if (!isValid) {\r\n");
      out.write("                        event.preventDefault(); // Prevent form submission if there are errors\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                function isValidEmail(email) {\r\n");
      out.write("                    // Basic email validation regex\r\n");
      out.write("                    const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("                    return emailRegex.test(email);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Mirrored from html.themegenix.com/skillgro/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 16 Sep 2024 01:45:08 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
