/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-09-28 08:19:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.authen;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"en\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/css-home.jsp", out, false);
      out.write("\n");
      out.write("        </head>\n");
      out.write("\n");
      out.write("        <body>\n");
      out.write("\n");
      out.write("            <!-- Scroll-top -->\n");
      out.write("            <button class=\"scroll__top scroll-to-target\" data-target=\"html\">\n");
      out.write("                <i class=\"tg-flaticon-arrowhead-up\"></i>\n");
      out.write("            </button>\n");
      out.write("            <!-- Scroll-top-end-->\n");
      out.write("\n");
      out.write("            <!-- header-area -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/header-home.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("            <!-- header-area-end -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- main-area -->\n");
      out.write("            <main class=\"main-area fix\">\n");
      out.write("\n");
      out.write("                <!-- breadcrumb-area -->\n");
      out.write("                <section class=\"breadcrumb__area breadcrumb__bg\" data-background=\"assets/img/bg/breadcrumb_bg.jpg\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <div class=\"breadcrumb__content\">\n");
      out.write("                                    <h3 class=\"title\">Student SingUp</h3>\n");
      out.write("                                    <nav class=\"breadcrumb\">\n");
      out.write("                                        <span property=\"itemListElement\" typeof=\"ListItem\">\n");
      out.write("                                            <a href=\"index.html\">Home</a>\n");
      out.write("                                        </span>\n");
      out.write("                                        <span class=\"breadcrumb-separator\"><i class=\"fas fa-angle-right\"></i></span>\n");
      out.write("                                        <span property=\"itemListElement\" typeof=\"ListItem\">SingUp</span>\n");
      out.write("                                    </nav>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"breadcrumb__shape-wrap\">\n");
      out.write("                        <img src=\"assets/img/others/breadcrumb_shape01.svg\" alt=\"img\" class=\"alltuchtopdown\">\n");
      out.write("                        <img src=\"assets/img/others/breadcrumb_shape02.svg\" alt=\"img\" data-aos=\"fade-right\" data-aos-delay=\"300\">\n");
      out.write("                        <img src=\"assets/img/others/breadcrumb_shape03.svg\" alt=\"img\" data-aos=\"fade-up\" data-aos-delay=\"400\">\n");
      out.write("                        <img src=\"assets/img/others/breadcrumb_shape04.svg\" alt=\"img\" data-aos=\"fade-down-left\" data-aos-delay=\"400\">\n");
      out.write("                        <img src=\"assets/img/others/breadcrumb_shape05.svg\" alt=\"img\" data-aos=\"fade-left\" data-aos-delay=\"400\">\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("                <!-- breadcrumb-area-end -->\n");
      out.write("\n");
      out.write("                <!-- singUp-area -->\n");
      out.write("                <section class=\"singUp-area section-py-120\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row justify-content-center\">\n");
      out.write("                            <div class=\"col-xl-6 col-lg-8\">\n");
      out.write("                                <div class=\"singUp-wrap\">\n");
      out.write("                                    <h2 class=\"title\">Create Your Account</h2>\n");
      out.write("                                    <div class=\"account__social\">\n");
      out.write("                                        <a href=\"https://accounts.google.com/o/oauth2/auth?scope=email profile openid&redirect_uri=http://localhost:9998/SWP_OCMS/LoginGoogleHandler&response_type=code&client_id=257748132214-9811944a5anccchj9egqhg9qci33l5ij.apps.googleusercontent.com&approval_prompt=force\" class=\"account__social-btn\">\n");
      out.write("                                            <img src=\"assets/img/icons/google.svg\" alt=\"img\">\n");
      out.write("                                            Continue with google\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"account__divider\">\n");
      out.write("                                        <span>or</span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <form action=\"authen?action=sign-up\" method=\"POST\" class=\"account__form\" id=\"signupForm\">\n");
      out.write("                                        <div class=\"form-grp\">\n");
      out.write("                                            <label for=\"email\">Email</label>\n");
      out.write("                                            <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"email\">\n");
      out.write("                                            <span class=\"error\" id=\"emailError\"></span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-grp\">\n");
      out.write("                                            <label for=\"password\">Password</label>\n");
      out.write("                                            <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"password\">\n");
      out.write("                                            <span class=\"error\" id=\"passwordError\"></span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-grp\">\n");
      out.write("                                            <label for=\"confirm-password\">Confirm Password</label>\n");
      out.write("                                            <input type=\"password\" name=\"confirmPassword\" id=\"confirm-password\" placeholder=\"Confirm Password\">\n");
      out.write("                                            <span class=\"error\" id=\"confirmPasswordError\"></span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <p style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<br></p>\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-two arrow-btn\">Sign Up<img src=\"assets/img/icons/right_arrow.svg\" alt=\"img\" class=\"injectable\"></button>\n");
      out.write("                                </form>\n");
      out.write("                                <div class=\"account__switch\">\n");
      out.write("                                    <p>Already have an account?<a href=\"authen?action=login\">Login</a></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            <!-- singUp-area-end -->\n");
      out.write("\n");
      out.write("        </main>\n");
      out.write("        <!-- main-area-end -->\n");
      out.write("\n");
      out.write("        <!-- footer-area -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/footer-home.jsp", out, false);
      out.write("\n");
      out.write("            <!-- footer-area-end -->\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- JS here -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/home/js-home.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            SVGInject(document.querySelectorAll(\"img.injectable\"));\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                const form = document.getElementById('signupForm');\n");
      out.write("                const email = document.getElementById('email');\n");
      out.write("                const password = document.getElementById('password');\n");
      out.write("                const confirmPassword = document.getElementById('confirm-password');\n");
      out.write("                const emailError = document.getElementById('emailError');\n");
      out.write("                const passwordError = document.getElementById('passwordError');\n");
      out.write("                const confirmPasswordError = document.getElementById('confirmPasswordError');\n");
      out.write("\n");
      out.write("                form.addEventListener('submit', function (event) {\n");
      out.write("                    let isValid = true;\n");
      out.write("\n");
      out.write("                    // Reset error messages\n");
      out.write("                    emailError.textContent = '';\n");
      out.write("                    passwordError.textContent = '';\n");
      out.write("                    confirmPasswordError.textContent = '';\n");
      out.write("\n");
      out.write("                    // Email validation\n");
      out.write("                    if (email.value.trim() === '') {\n");
      out.write("                        emailError.textContent = 'Email is required';\n");
      out.write("                        isValid = false;\n");
      out.write("                    } else if (!isValidEmail(email.value)) {\n");
      out.write("                        emailError.textContent = 'Please enter a valid email address';\n");
      out.write("                        isValid = false;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    // Password validation\n");
      out.write("                    if (password.value.trim() === '') {\n");
      out.write("                        passwordError.textContent = 'Password is required';\n");
      out.write("                        isValid = false;\n");
      out.write("                    } else if (password.value.length < 8) {\n");
      out.write("                        passwordError.textContent = 'Password must be at least 8 characters long';\n");
      out.write("                        isValid = false;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    // Confirm Password validation\n");
      out.write("                    if (confirmPassword.value.trim() === '') {\n");
      out.write("                        confirmPasswordError.textContent = 'Please confirm your password';\n");
      out.write("                        isValid = false;\n");
      out.write("                    } else if (password.value !== confirmPassword.value) {\n");
      out.write("                        confirmPasswordError.textContent = 'Passwords do not match';\n");
      out.write("                        isValid = false;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    if (!isValid) {\n");
      out.write("                        event.preventDefault(); // Prevent form submission if there are errors\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                function isValidEmail(email) {\n");
      out.write("                    // Basic email validation regex\n");
      out.write("                    const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\n");
      out.write("                    return emailRegex.test(email);\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
