/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-06-03 02:46:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Human;
import model.HumanType;
import dal.DBContext;
import java.util.ArrayList;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("dal.DBContext");
    _jspx_imports_classes.add("model.HumanType");
    _jspx_imports_classes.add("model.Human");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>List human</title>\n");
      out.write("        ");
 ArrayList<Human> list = (ArrayList<Human>)request.getAttribute("humans"); 
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <style>\n");
      out.write("            table{\n");
      out.write("                border-collapse: collapse;\n");
      out.write("                width: 50%;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <a href=\"insert.jsp\">Insert new human</a>\n");
      out.write("        <table border=\"1\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID</th>\n");
      out.write("                    <th>Name</th>\n");
      out.write("                    <th>DOB</th>\n");
      out.write("                    <th>Gender</th>\n");
      out.write("                    <th>Type</th>\n");
      out.write("                    <th colspan=\"2\">Option</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>            \n");
      out.write("                ");
 if (list != null) {
                    for(Human x : list) { 
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td name=\"id\">");
      out.print( x.getID());
      out.write("</td>\n");
      out.write("                    <td name=\"name\">");
      out.print( x.getName() );
      out.write("</td>\n");
      out.write("                    <td name=\"dob\">");
      out.print( x.getDob() );
      out.write("</td>\n");
      out.write("                    <td name=\"gender\">");
      out.print( x.isGender() ? "Male" : "Female" );
      out.write("</td>\n");
      out.write("                    <td name=\"type\">");
      out.print( x.getType().getName() );
      out.write("</td>\n");
      out.write("                    <td> \n");
      out.write("                        <a href=\"#\" onclick=\"update(this)\">Edit</a> \n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("                        <form action=\"delete\" method=\"post\" onsubmit=\"return confirm('Are you sure you want to delete this human?');\">\n");
      out.write("                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( x.getID() );
      out.write("\">\n");
      out.write("                            <input type=\"submit\" value=\"Delete\">\n");
      out.write("                        </form>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                ");
 } }
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <form style=\"display: none\" id=\"form-update\" action=\"update\" method=\"post\">\n");
      out.write("            <h1>Update form</h1>\n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <td><label for=\"id\">ID</label></td>\n");
      out.write("                    <td><input type=\"text\" name=\"id\" value=\"\" readonly></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td><label for=\"name\">Name</label></td>\n");
      out.write("                    <td><input type=\"text\" name=\"name\" value=\"\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td><label for=\"dob\">Date of Birth</label></td>\n");
      out.write("                    <td><input type=\"date\" name=\"dob\" value=\"\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td><label for=\"gender\">Gender</label></td>\n");
      out.write("                    <td>\n");
      out.write("                        <select name=\"gender\" >\n");
      out.write("                            <option value=\"true\">Male</option>\n");
      out.write("                            <option value=\"false\">Female</option>\n");
      out.write("                        </select>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td><label for=\"type\">Type</label></td>\n");
      out.write("                    <td>\n");
      out.write("                        <select name=\"type\">\n");
      out.write("                            ");
 
                                // Fetch HumanType list from the request attribute
                                DBContext db = new DBContext();
                                ArrayList<HumanType> types = db.getTypes();
                                for (HumanType type : types) {
                            
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( type.getTypeiD() );
      out.write('"');
      out.write('>');
      out.print( type.getName() );
      out.write("</option>\n");
      out.write("                            ");
 
                                }
                            
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td></td>\n");
      out.write("                    <td align=\"\">\n");
      out.write("                        <button type=\"submit\">Update</button>\n");
      out.write("                        <button type=\"reset\">Reset</button>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            function update(e) {\n");
      out.write("                // Show the update form\n");
      out.write("                displayOrHideForm();\n");
      out.write("\n");
      out.write("                // Get the nearest tr element\n");
      out.write("                let tr = e.closest(\"tr\");\n");
      out.write("\n");
      out.write("                // Get the values from the tr element\n");
      out.write("                let id = tr.querySelector(\"td[name='id']\").innerText;\n");
      out.write("                let name = tr.querySelector(\"td[name='name']\").innerText;\n");
      out.write("                let dob = tr.querySelector(\"td[name='dob']\").innerText;\n");
      out.write("                let gender = tr.querySelector(\"td[name='gender']\").innerText === \"Male\";\n");
      out.write("                let type = tr.querySelector(\"td[name='type']\").innerText;\n");
      out.write("\n");
      out.write("                // Get the form and input elements\n");
      out.write("                let form = document.querySelector(\"#form-update\");\n");
      out.write("\n");
      out.write("                let idInput = form.querySelector(\"input[name='id']\");\n");
      out.write("                let nameInput = form.querySelector(\"input[name='name']\");\n");
      out.write("                let dobInput = form.querySelector(\"input[name='dob']\");\n");
      out.write("                let genderInput = form.querySelector(\"select[name='gender']\");\n");
      out.write("                let typeInput = form.querySelector(\"select[name='type']\");\n");
      out.write("\n");
      out.write("                // Set the values to the form inputs\n");
      out.write("                idInput.value = id;\n");
      out.write("                nameInput.value = name;\n");
      out.write("                dobInput.value = new Date(dob).toISOString().substring(0, 10); // Format date to YYYY-MM-DD\n");
      out.write("                genderInput.value = gender;\n");
      out.write("                typeInput.value = Array.from(typeInput.options).find(option => option.text === type).value;\n");
      out.write("                /*\n");
      out.write(" Array.from(typeInput.options): typeInput.options là một tập hợp các phần tử <option> trong thẻ <select>. Array.from() được sử dụng để chuyển đổi tập hợp này thành một mảng.\n");
      out.write("\n");
      out.write(".find(option => option.text === type): Phương thức find() được sử dụng để tìm kiếm phần tử đầu tiên trong mảng thỏa mãn điều kiện được cung cấp. Ở đây, chúng ta đang tìm phần tử <option> có thuộc tính text bằng với giá trị của biến type.\n");
      out.write("\n");
      out.write(".value: Khi phần tử <option> thỏa mãn điều kiện được tìm thấy, chúng ta sử dụng thuộc tính value của nó. Điều này trả về giá trị của phần tử <option>, thường được sử dụng khi chúng ta muốn gán giá trị cho một trường input.\n");
      out.write("                 */\n");
      out.write("                \n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function displayOrHideForm() {\n");
      out.write("                let form = document.querySelector(\"#form-update\");\n");
      out.write("                form.style.display = form.style.display === \"none\" ? \"block\" : \"none\";\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
