/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2025-03-14 09:09:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.job;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addJob_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1740624262026L));
    _jspx_dependants.put("jar:file:/D:/Specialization/25_spring/FA/MOCK/ims_team_2.1/target/IMS-1.0/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Job</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/assets/BUTTONS.css\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/assets/tags/dropdown.css\"/>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/navbarCss.jsp", out, true);
      out.write("\r\n");
      out.write("        </head>\r\n");
      out.write("        <body>\r\n");
      out.write("            <div class=\"main-container\">\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/navbar.jsp", out, true);
      out.write("\r\n");
      out.write("                <div class=\"content-wrapper\">\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/horizontalBar.jsp", out, true);
      out.write("\r\n");
      out.write("                    <main class=\"content-area\">\r\n");
      out.write("                        <form action=\"addJob\" method=\"post\" id=\"createJobForm\">\r\n");
      out.write("                            <div class=\"container-fluid\">\r\n");
      out.write("                                <p class=\"mb-4 fs-4\">\r\n");
      out.write("                                    <span><u>Job list</u></span>\r\n");
      out.write("                                    <span><b> > </b></span>\r\n");
      out.write("                                    <span><u>Create job</u></span>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"container pb-5\" style=\"background: #E5FEFF\">\r\n");
      out.write("                                <!-- Row 1 -->\r\n");
      out.write("                                <div class=\"row align-items-center pt-4\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3\">\r\n");
      out.write("                                                <h6 class=\"mb-0\"><span>Job title </span><span style=\"color: red\">*</span></h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <input name=\"jobTitle\" type=\"text\" class=\"form-control form-control-sm\"\r\n");
      out.write("                                                       placeholder=\"Type a title...\" required/>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3 offset-2\">\r\n");
      out.write("                                                <h6 class=\"mb-0\"><span>Skills </span><span style=\"color: red\">*</span></h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <div id=\"multiSelectBox1\" class=\"multi-select-container form-control form-control-sm\">\r\n");
      out.write("                                                    <div id=\"selectedTags1\" class=\"selected-tags\"></div>\r\n");
      out.write("                                                    <div id=\"dropdownList1\" class=\"dropdown-list\"></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Row 2 -->\r\n");
      out.write("                                <div class=\"row align-items-center pt-4\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3\">\r\n");
      out.write("                                                <h6 class=\"mb-0\"><span>Start Date </span><span style=\"color: red\">*</span></h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <input name=\"startDate\" type=\"datetime-local\" class=\"form-control form-control-sm\" required/>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3 offset-2\">\r\n");
      out.write("                                                <h6 class=\"mb-0\"><span>End Date </span><span style=\"color: red\">*</span></h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <input name=\"endDate\" type=\"datetime-local\" class=\"form-control form-control-sm\" required/>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Row 3 -->\r\n");
      out.write("                                <div class=\"row align-items-center pt-4\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3\">\r\n");
      out.write("                                                <h6 class=\"mb-0\">Salary Range <span style=\"color: red\">*</span> </h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <div class=\"row align-items-center\">\r\n");
      out.write("                                                    <div class=\"col-md-2\">\r\n");
      out.write("                                                        <d style=\"font-size: 15px\">From</d>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-md-4\">\r\n");
      out.write("                                                        <input name=\"salaryFrom\" type=\"number\" class=\"form-control form-control-sm\" required/>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-md-1 offset-1\">\r\n");
      out.write("                                                        <d style=\"font-size: 15px\">To</d>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-md-4\">\r\n");
      out.write("                                                        <input name=\"salaryTo\" type=\"number\" class=\"form-control form-control-sm\" required/>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3 offset-2\">\r\n");
      out.write("                                                <h6 class=\"mb-0\"><span>Benefits </span><span style=\"color: red\">*</span></h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <div id=\"multiSelectBox2\" class=\"multi-select-container form-control form-control-sm\">\r\n");
      out.write("                                                    <div id=\"selectedTags2\" class=\"selected-tags\"></div>\r\n");
      out.write("                                                    <div id=\"dropdownList2\" class=\"dropdown-list\"></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Row 4 -->\r\n");
      out.write("                                <div class=\"row align-items-center pt-4\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3\">\r\n");
      out.write("                                                <h6 class=\"mb-0\" style=\"white-space: nowrap\">Working address <span style=\"color: red\">*</span></h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <input name=\"workingAddress\" type=\"text\" class=\"form-control form-control-sm\"\r\n");
      out.write("                                                       placeholder=\"Type an address\" required/>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                            <div class=\"col-md-3 offset-2\">\r\n");
      out.write("                                                <h6 class=\"mb-0\"><span>Level </span><span style=\"color: red\">*</span></h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <div id=\"multiSelectBox3\" class=\"multi-select-container form-control form-control-sm\">\r\n");
      out.write("                                                    <div id=\"selectedTags3\" class=\"selected-tags\"></div>\r\n");
      out.write("                                                    <div id=\"dropdownList3\" class=\"dropdown-list\"></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Row 5 -->\r\n");
      out.write("                                <div class=\"row align-items-center pt-4\">\r\n");
      out.write("                                    <div class=\"col-md-6 offset-6\">\r\n");
      out.write("                                        <div class=\"row align-items-top\">\r\n");
      out.write("                                            <div class=\"col-md-3 offset-2\">\r\n");
      out.write("                                                <h6 class=\"mb-0\">Description</h6>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-7\">\r\n");
      out.write("                                                <textarea name=\"description\" class=\"form-control\" style=\"height: 150px\"></textarea>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Buttons -->\r\n");
      out.write("                                <div class=\"row align-items-center\" style=\"margin-top: 100px\">\r\n");
      out.write("                                ");
      out.print( request.getAttribute("errorMessage") != null ? request.getAttribute("errorMessage") : "" );
      out.write("\r\n");
      out.write("                                ");
      out.print( request.getAttribute("errorMessage2") != null ? request.getAttribute("errorMessage2") : "" );
      out.write("\r\n");
      out.write("                                <div class=\"col-md-2 offset-4\">\r\n");
      out.write("                                    <button class=\"button-1\" role=\"button\" type=\"submit\">Submit</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-2\">\r\n");
      out.write("                                    <button class=\"button-1\" role=\"button\" type=\"reset\">Cancel</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </main>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/assets/tags/dropdown.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
