/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2025-03-14 08:34:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.authen;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1740624262026L));
    _jspx_dependants.put("jar:file:/D:/Specialization/25_spring/FA/MOCK/ims_team_2.1/target/IMS-1.0/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Login</title>\r\n");
      out.write("        <meta charset=\"UTF-8\"/>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./view/assets/styles.css\"/>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <main class=\"container d-flex justify-content-center align-items-center min-vh-100\">\r\n");
      out.write("            <div class=\"row justify-content-center w-100\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-5 mw-500\">\r\n");
      out.write("                    <div class=\"card shadow\" style=\"background: linear-gradient(to right, #CCCCCC, #DDDDDD);\">\r\n");
      out.write("                        <div class=\"card-body p-5\">\r\n");
      out.write("                            <h1 class=\"card-title text-center mb-4\">IMS Recruitment</h1>\r\n");
      out.write("\r\n");
      out.write("                            <form id=\"loginForm\" action=\"login\" method=\"post\">\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label for=\"username\" class=\"form-label\">Username</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\" placeholder=\"Enter your username\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label for=\"password\" class=\"form-label\">Password</label>\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\"\r\n");
      out.write("                                               placeholder=\"Enter your password\" required>\r\n");
      out.write("                                        <button class=\"btn btn-outline-secondary toggle-password\" type=\"button\" tabindex=\"-1\">\r\n");
      out.write("                                            <i class=\"bi bi-eye-slash\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                ");

                                    String successMessage = (String) request.getAttribute("successMessage");
                                    String errorMessage = (String) request.getAttribute("errorMessage");
                                    if (errorMessage != null) {
                                
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                                    ");
      out.print( errorMessage );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 }
                                    if(successMessage != null){
                                
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("                                    ");
      out.print( successMessage );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"mb-3 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <input type=\"checkbox\" class=\"form-check-input\" id=\"rememberMe\" name=\"rememberMe\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"rememberMe\">Remember me</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <a href=\"forgotPassword\" class=\"text-decoration-none\">Forgot password?</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"d-grid gap-2\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary btn-lg\">Sign In</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("<!--    <label for=\"fruits\">Choose fruits:</label>\r\n");
      out.write("        <select id=\"fruits\" name=\"fruits\" multiple>\r\n");
      out.write("            <option value=\"apple\">Apple</option>\r\n");
      out.write("            <option value=\"banana\">Banana</option>\r\n");
      out.write("            <option value=\"mango\">Mango</option>\r\n");
      out.write("            <option value=\"orange\">Orange</option>\r\n");
      out.write("            <option value=\"apple\">Apple</option>\r\n");
      out.write("            <option value=\"banana\">Banana</option>\r\n");
      out.write("            <option value=\"mango\">Mango</option>\r\n");
      out.write("            <option value=\"orange\">Orange</option>\r\n");
      out.write("        </select>-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("                const togglePasswordButton = document.querySelector('.toggle-password');\r\n");
      out.write("                const passwordInput = document.getElementById('password');\r\n");
      out.write("\r\n");
      out.write("                togglePasswordButton.addEventListener('click', function () {\r\n");
      out.write("                    const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';\r\n");
      out.write("                    passwordInput.setAttribute('type', type);\r\n");
      out.write("\r\n");
      out.write("                    const icon = this.querySelector('i');\r\n");
      out.write("                    icon.classList.toggle('bi-eye-slash');\r\n");
      out.write("                    icon.classList.toggle('bi-eye');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
